### ISSUE TITLE
Status left as Loading for no results

### ISSUE THREAD

**Issue by awbrooke824** [coveooss/lwc-coveobot#10] opened 2021-04-20 19:31 UTC
Customer is reporting a Loading state when no results are returned. This causes confusion for the user as it doesn't provide any visual change the anything has completed and there were no results.

In file lwcChatbotQuery.html, I see in the template that the spinner is left when no results are returned.

<template if:true={hasResults}>
        <template iterator:it={resultsToDisplay}>
            <c-lwc-coveo-result result={it.value} key={it.value.uniqueId} onresultclick={resultClickHandler} rank={it.value.rank}></c-lwc-coveo-result>
        </template>
    </template>
    <template if:false={hasResults}>
        <lightning-spinner alternative-text="Loading" size="small"></lightning-spinner>
    </template>

Ideally this would show that no results returned, unless there's a config for no results and this customer hasn't set it up yet.

Thanks

**Comment by erocheleau** [comment] 2021-04-27 19:03
Duplicate of https://github.com/coveooss/lwc-coveobot/issues/7

**Closed** 2021-04-27 19:03 UTC
